import initScrollSuave from "./modules/scrollSuave.js";
import initAnimaScroll from "./modules/scroll-animacao.js";
import initAccordion from "./modules/accordion.js";
import initTabNav from "./modules/tabNav.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropDown from "./modules/dropdown-menu.js";
// import outsideClick from "./modules/outsideClick.js";
import aula from "./modules/aula.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initAnimaNumeros from "./modules/anima-numeros.js";
import initFuncionamento from "./modules/funcionamento.js";

initScrollSuave();
initAnimaScroll();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropDown();
// outsideClick();
aula();
initMenuMobile();
initAnimaNumeros();
initFuncionamento();
